workflows:
  android-native-build:
    name: Android Native (Java/Kotlin/C++) Build
    environment:
      android_sdk: default
      java: 17
    scripts:
      - name: Cấp quyền thực thi cho Gradle
        script: |
          chmod +x gradlew
      - name: Build file APK (Debug)
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
