workflows:
  android-native-build:
    name: Android Native Build
    environment:
      android_sdk: default
      java: 17
    scripts:
      - name: Build file APK (Debug)
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
      
